WIP still need to finish balance
Nearly there, but balance is not being returned to the balance client:

assertion failed: `assert_contains!(container, containee)`
 container label: `balance_output`,
 container debug: `""`,
 containee label: `&balance.to_string()`,
 containee debug: `"1000"`
thread 'acceptance_tests::tests::account_creation_and_balance' panicked at src/acceptance_tests.rs:167:9: